BEGIN;
ALTER TABLE c_base.aguas_continentales RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.aguas_continentales ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.aguas_continentales ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'MULTIPOLYGON'::text OR geom IS NULL);
ALTER TABLE c_base.aguas_continentales ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.aguas_continentales DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.aguas_continentales DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.aguas_continentales DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.batimetria RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.batimetria ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.batimetria ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'MULTIPOLYGON'::text OR geom IS NULL);
ALTER TABLE c_base.batimetria ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.batimetria DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.batimetria DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.batimetria DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.bosques_pais RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.bosques_pais ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.bosques_pais ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'MULTIPOLYGON'::text OR geom IS NULL);
ALTER TABLE c_base.bosques_pais ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.bosques_pais DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.bosques_pais DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.bosques_pais DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.cantones RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.cantones ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.cantones ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'MULTIPOLYGON'::text OR geom IS NULL);
ALTER TABLE c_base.cantones ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.cantones DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.cantones DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.cantones DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.cuencas RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.cuencas ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.cuencas ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'MULTIPOLYGON'::text OR geom IS NULL);
ALTER TABLE c_base.cuencas ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.cuencas DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.cuencas DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.cuencas DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.curvas_nivel_100m_poligono RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.curvas_nivel_100m_poligono ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.curvas_nivel_100m_poligono ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'MULTIPOLYGON'::text OR geom IS NULL);
ALTER TABLE c_base.curvas_nivel_100m_poligono ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.curvas_nivel_100m_poligono DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.curvas_nivel_100m_poligono DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.curvas_nivel_100m_poligono DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.departamentos RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.departamentos ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.departamentos ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'MULTIPOLYGON'::text OR geom IS NULL);
ALTER TABLE c_base.departamentos ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.departamentos DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.departamentos DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.departamentos DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.el_salvador RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.el_salvador ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.el_salvador ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'MULTIPOLYGON'::text OR geom IS NULL);
ALTER TABLE c_base.el_salvador ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.el_salvador DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.el_salvador DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.el_salvador DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.municipios RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.municipios ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.municipios ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'MULTIPOLYGON'::text OR geom IS NULL);
ALTER TABLE c_base.municipios ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.municipios DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.municipios DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.municipios DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.resto_paises_mesoamerica RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.resto_paises_mesoamerica ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.resto_paises_mesoamerica ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'MULTIPOLYGON'::text OR geom IS NULL);
ALTER TABLE c_base.resto_paises_mesoamerica ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.resto_paises_mesoamerica DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.resto_paises_mesoamerica DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.resto_paises_mesoamerica DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.areas_protegidas RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.areas_protegidas ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.areas_protegidas ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'POINT'::text OR geom IS NULL);
ALTER TABLE c_base.areas_protegidas ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.areas_protegidas DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.areas_protegidas DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.areas_protegidas DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.cabecera_municipal RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.cabecera_municipal ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.cabecera_municipal ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'POINT'::text OR geom IS NULL);
ALTER TABLE c_base.cabecera_municipal ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.cabecera_municipal DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.cabecera_municipal DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.cabecera_municipal DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.casas_cultura RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.casas_cultura ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.casas_cultura ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'POINT'::text OR geom IS NULL);
ALTER TABLE c_base.casas_cultura ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.casas_cultura DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.casas_cultura DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.casas_cultura DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.centros_educativos RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.centros_educativos ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.centros_educativos ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'POINT'::text OR geom IS NULL);
ALTER TABLE c_base.centros_educativos ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.centros_educativos DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.centros_educativos DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.centros_educativos DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.centros_salud RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.centros_salud ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.centros_salud ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'POINT'::text OR geom IS NULL);
ALTER TABLE c_base.centros_salud ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.centros_salud DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.centros_salud DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.centros_salud DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.ciudades RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.ciudades ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.ciudades ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'POINT'::text OR geom IS NULL);
ALTER TABLE c_base.ciudades ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.ciudades DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.ciudades DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.ciudades DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.fuentes RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.fuentes ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.fuentes ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'POINT'::text OR geom IS NULL);
ALTER TABLE c_base.fuentes ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.fuentes DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.fuentes DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.fuentes DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.pozos RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.pozos ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.pozos ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'POINT'::text OR geom IS NULL);
ALTER TABLE c_base.pozos ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.pozos DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.pozos DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.pozos DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.carreteras RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.carreteras ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.carreteras ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'MULTILINESTRING'::text OR geom IS NULL);
ALTER TABLE c_base.carreteras ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.carreteras DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.carreteras DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.carreteras DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.curvas_nivel_10m RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.curvas_nivel_10m ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.curvas_nivel_10m ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'MULTILINESTRING'::text OR geom IS NULL);
ALTER TABLE c_base.curvas_nivel_10m ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.curvas_nivel_10m DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.curvas_nivel_10m DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.curvas_nivel_10m DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
ALTER TABLE c_base.rios RENAME COLUMN the_geom TO geom;
ALTER TABLE c_base.rios ADD constraint enforce_dims_geom CHECK (ndims(geom) = 2);
ALTER TABLE c_base.rios ADD CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'MULTILINESTRING'::text OR geom IS NULL);
ALTER TABLE c_base.rios ADD CONSTRAINT enforce_srid_geom CHECK (srid(geom) = 32616);
ALTER TABLE c_base.rios DROP CONSTRAINT enforce_dims_the_geom;
ALTER TABLE c_base.rios DROP CONSTRAINT enforce_geotype_the_geom;
ALTER TABLE c_base.rios DROP CONSTRAINT enforce_srid_the_geom;
END;
BEGIN;
SELECT probe_geometry_columns();
END;
